### ISSUE TITLE
Removal request: cracked Minecraft launcher

### ISSUE THREAD

**Issue by kb-1000** [flathub/org.tlauncher.TLauncher#9]
This is a cracked Minecraft launcher. Please remove it from the Flathub repository.

**Comment by pizzadude** [comment]
It has a useful mod installer so I'd say that it's more than just a cracked Minecraft launcher.

**Comment by kb-1000** [comment]
True, true. Illegal mod reposting on top of being a cracked launcher.

**Comment by jurf** [comment]
The sole reason I bothered with adding this here was because of the pandemic. I’d argue for leaving this here until things get back to normal; after that, I don’t really care.

**Comment by kb-1000** [comment]
Why?
Are you associated with Mojang in any way that grants you the right to give away "free copies" of Minecraft?

**Comment by pizzadude** [comment]
@kb-1000 Flathub doesn't distribute free copies of Minecraft.

**Comment by jurf** [comment]
Of course not. Please refrain from sarcasm. I did not mock you either.

Minecraft is the most popular video game on the planet. We are also in a pandemic, people are locked up, and mental health is generally really low. Being able to pull someone into a Minecraft server easily is a great way to sustain human connections temporarily.

Besides, you cannot play on official servers with this version; hardly a ‘free copy’. Not speaking about the minuscule impact this package has – last time I checked there were a few thousand downloads.

My case is that in an age of crisis, copyright law is slightly less important than usual. In a few months – sure, tear this down. But until then, I consider this human.

**Comment by glodomorrapl** [comment]
> My case is that in an age of crisis, copyright law is slightly less important than usual.

making it easier for people to steal someone else's work because there's a pandemic is fine for you? excuse me, but who do you think you are exactly? 

no, "you cannot play on official servers" is not a valid argument.

minecraft is not the only way for people to deal with mental health issues. you have tons of other free games out there you can use for that, and a hundred different communicators to maintain "human connections".

i think someone needs to give mojang/microsoft a hint about this repo, they might just send you a dmca complaint for your efforts c:

**Comment by pizzadude** [comment]
@glodomorrapl bootlicker

**Comment by glodomorrapl** [comment]
@pizzadude freeloader

buy the game and stop defending cracked launchers lmao

**Comment by pizzadude** [comment]
@glodomorrapl I bought the game 10 years ago during Minecraft beta. I use this launcher for the mod browser.

**Comment by kb-1000** [comment]
Which is, as mentioned above, just a bunch of illegally reposted mods.
https://vazkii.net/repost/

**Comment by pizzadude** [comment]
Sharing is caring.

**Comment by whitebeartigtig** [comment]
doesn't make it any less illegal

**Comment by pizzadude** [comment]
This thread reeks of corporate shilling.

**Comment by pizzadude** [comment]
There are better things to do than REEEEEEEEEE on the internet because there's a flatpak manifest on github for a program that allows you to get the worlds best selling game by one of the worlds biggest software companies without paying.

If you love simping for big corporations that much, kindly fuck off back to Windows / Macintosh.

**Comment by kb-1000** [comment]
Is Linux about piracy?
I would think no, thus you're wrong.
Also, if there just was a flatpak manifest somewhere out there... would I care? No.
However, Flathub is the largest Flatpak repository out there, putting piracy in there doesn't seem like a good idea.

**Comment by pizzadude** [comment]
https://www.gnu.org/philosophy/words-to-avoid.en.html

“Piracy”
Publishers often refer to copying they don't approve of as “piracy.” In this way, they imply that it is ethically equivalent to attacking ships on the high seas, kidnapping and murdering the people on them. Based on such propaganda, they have procured laws in most of the world to forbid copying in most (or sometimes all) circumstances. (They are still pressuring to make these prohibitions more complete.)

If you don't believe that copying not approved by the publisher is just like kidnapping and murder, you might prefer not to use the word “piracy” to describe it. Neutral terms such as “unauthorized copying” (or “prohibited copying” for the situation where it is illegal) are available for use instead. Some of us might even prefer to use a positive term such as “sharing information with your neighbor.”

A US judge, presiding over a trial for copyright infringement, recognized that “piracy” and “theft” are smear words.

**Comment by barthalion** [comment]
We're going to discuss the issue internally.

**Comment by jurf** [comment]
I don’t really have time for this; I’m free to discuss ethics over a beer in Brno next year. @barthalion I don’t have the right to remove this repo, should I just do an EOL and it will get removed later?

**Comment by barthalion** [comment]
The app has been deleted from Flathub.
